---
title: "Multiple Atrial Tachycardias"
subtitle: "Clinical Case Conference"
author: Anish S. Shah, MD, MS
institute: Division of Cardiology, University of Utah
date: May 14, 2025
format:
  revealjs:
    transition: fade
    transition-speed: fast
    slide-number: true
    incremental: true
    auto-animate-easing: ease-in-out
    auto-animate-unmatched: false
    progress: true
    chalkboard: true
    scrollable: true

csl: ../../apa.csl
---

# T0370 (2024-12-13) {background-color='{{< brand color primary >}}'}

## History 

. . .

**HPI**: 59M with recurrent SVT, dx in 09/2023 peri-operatively (umbilical hernia repair), with subsequent MCT showing maximum duration of ~2 minutes. EPS in 02/2024 non-inducible.

. . .

**Hx**: DMT2 c/b neuropathy, ETOH/THC usage, lives alone in Ogden

. . .

**Meds**: duloxetine, gabapentin, metoprolol succinate 25, *no allergies*

## Physical 

. . .

**Exam**: 91 bpm, 118/76, 96% on RA. AOx4, thin gentleman, S1/S2 without M/G/R. Easy WOB with symmetrical chest rise. Antalgic gait (cane). 

. . .

**Studies**: LVEF 65% with normal filling pressures. MCT with 4k runs of SVT, longest 2 minutes (symptomatic).

# Electrophysiology Study {background-color='{{< brand color primary >}}'}

---

- Four catheter EP study
- RCFV = 8F quadrapolar HRA, 7F hexapolar CRD2 for His
- LCFV = 8F decapolar CS, 7F quadrapolar RV
- EAM = ESI
- Mapping = quadraspline grid catheter for mapping
- Ablator = irrigated 3.5 mm force-sensing

# Baseline {background-color='{{< brand color primary >}}'}

## {background-image="map-sinus-catheter-positions.jpg" background-size="contain"}
## {background-image="map-sinus-activation.jpg" background-size="contain"}
## {background-image="map-sinus-activation-2.jpg" background-size="contain"}

## {background-image="bl-intervals.png" background-size="contain"}
## {background-image="bl-rv-600.png" background-size="contain"}
## {background-image="bl-rv-600-pvc-during-pacing.png" background-size="contain"}

::: {.notes}
PVC comes in early to pacing, leading to pacing into refractory tissue. Morphology consistent with catheter bump.
:::

## {background-image="bl-rv-510-wbcl.png" background-size="contain"}
## {background-image="bl-rv-490-wbcl.png" background-size="contain"}

::: {.notes}
The retrograde block actually comes with a narrow QRS morphlogy, suggesting His capture. RV lead is basal (positive in V6 when just having myocardial capture).
:::

## {background-image="bl-vest-rv-600-430-va-190.png" background-size="contain"}
## {background-image="bl-vest-rv-600-420-va-300-retrograde-jump.png" background-size="contain"}
## {background-image="bl-vest-rv-600-230-ventricular-frp.png" background-size="contain"}
## {background-image="bl-vest-rv-600-220-verp-not-reached-vaerp.png" background-size="contain"}
## {background-image="bl-rv-240-wcl-shorter.png" background-size="contain"}

## {background-image="bl-hra-600-normal-activation-sequence.png" background-size="contain"}
## {background-image="bl-hra-600-frequent-pac-switch-to-cs-pacing.png" background-size="contain"}

::: {.notes}
With HRA pacing, had *lots* of ectopy leading to us moving to pacing from CS proximal instead.
:::

## {background-image="bl-cs-380-pac-330-averp.png" background-size="contain"}

::: {.notes}
Attempting to find Wenckebach but had frequent PAC, switch surrogate as an S2 to test refractoriness.
:::

## {background-image="bl-cs-600-240-avn-erp.png" background-size="contain"}

::: {.notes}
Skipped to AVNERP because we induced with atrial pacing while checking Wenckebach. 
:::

## {background-image="bl-parahissian-nodal-response.png" background-size="contain"}


# Tachycardia #1 {background-color='{{< brand color primary >}}'}

## {background-image="tach-onset-with-aberrancy-tcl-280.png" background-size="contain"}

## {background-image="tach-tcl-250-vop-230-fails-to-entrain.png" background-size="contain"}
## {background-image="tach-tcl-250-atrial-entrainment-230-onset.png" background-size="contain"}
## {background-image="tach-tcl-250-broke-during-entrainment-ppi-270.png" background-size="contain"}
## {background-image="tach-tcl-250-entrainment-from-cs-220-ppi-300.png" background-size="contain"}

## {background-image="tach-pacing-in-sinus-cs-250-ah-80.png" background-size="contain"}

::: {.notes}
Pacing during sinus rhythm at approximately the same cycle length as tachycardia. The AH interval is approximately 80 ms. We can then compare AH interval during tachycardia.
:::

## {background-image="tach-tcl-250-narrow-ah-71.png" background-size="contain"}

::: {.notes}
The tachcyardia, of a similar cycle length, has an AH interval that is approximately the same as that during sinus pacing. About 71 ms.
:::

## {background-image="tach-tcl-280-aberrancy-ah-95.png" background-size="contain"}

::: {.notes}
The surface leads show change in morphology, suggesting left bundle aberrancy. The AH interval is the same during this however, approximately 90 miliseconds.
:::

{{< include ../../_includes/eps/maneuver-delta-ah.qmd >}}

## {background-image="map-at-his-position.jpg" background-size="contain"}
## {background-image="map-at-earliest-septum.jpg" background-size="contain"}

## {background-image="abl-frequent-pac-while-on-septum.png" background-size="contain"}
## {background-image="map-ablate-septum.jpg" background-size="contain"}

## {background-image="map-transition-to-other-at.jpg" background-size="contain"}

::: {.notes}
Recurrent arrhythmia however, but the activation sequence changes. CS 5-6 is now earliest.
:::

## {background-image="map-at-not-on-right.jpg" background-size="contain"}
## {background-image="map-at-not-on-right-2.jpg" background-size="contain"}

# Transeptal Puncture {background-color='{{< brand color primary >}}'}

---

- Due to eccentric activation on CS, planned transeptal
- Previously ablated on anteroseptum, subsequent tissue edema on ICE
- AcQCross with needle and with electrocautery did not pass dilator
- Exchanged for Agilis with BRK1 $\rightarrow$ support for transeptal

# Tachycardia #2 {background-color='{{< brand color primary >}}'}

## {background-image="tach-2-earliest-mid-cs-tcl-250.png" background-size="contain"}
## {background-image="tach-2-tcl-310-stable-eccentric.png" background-size="contain"}
## {background-image="tach-2-transition-earliest-cs-mid.png" background-size="contain"}
## {background-image="tach-la-tcl-310-grid.png" background-size="contain"}

::: {.notes}
We decide to use the grid to help map the LA, as has never had AF or PVI prior. Initially place grid in the LV and move up. Highlighting some fractionation and late potentials at the annulus.
:::

## {background-image="map-la-voltage.jpg" background-size="contain"}
## {background-image="map-la-lat.jpg" background-size="contain"}
## {background-image="map-la-vectors.jpg" background-size="contain"}
## {background-image="map-la-earliest-site.jpg" background-size="contain"}
## {background-image="map-ablate-la-anterior.jpg" background-size="contain"}
## {background-image="map-ablate-la-anterior-2.jpg" background-size="contain"}

# Post {background-color='{{< brand color primary >}}'}

## {background-image="post-hv-56.png" background-size="contain"}
## {background-image="post-induction-no-arrhythmia.png" background-size="contain"}

## {background-image="ra-at-activation.gif" background-size="contain"}
## {background-image="map-final-septal-at.jpg" background-size="contain"}

## {background-image="la-at-activation.gif" background-size="contain"}
## {background-image="map-final-la-at.jpg" background-size="contain"}
