---
title: "Para-Hisian PVC"
subtitle: M&M Conference
author: Anish S. Shah, MD, MS
institute: Division of Cardiology, University of Utah
date: December 20, 2024
format:
  revealjs:
    transition: fade
    transition-speed: fast
    slide-number: true
    incremental: true
    auto-animate-easing: ease-in-out
    auto-animate-unmatched: false
    progress: true
    chalkboard: true
    scrollable: true
    height: 1080
    width: 1920

csl: ../../apa.csl
---

# F8270 2024-12-05

## History & Physical

::::: {.columns}
::: {.column width="50%"}
**HPI**: 78M with NICM s/p DC-ICD with amiodarone intolerance presents for PVC ablation

**PMHx**: NICM, HFimpEF (10% in 2019 to 40% in 2023), non-obstructive CAD, cardiogenic shock & VT storm s/p DC-ICD in 2011, amiodarone-induced hypothyroidism, HTN, HLD, pxAF, CKDIII

**Social**: Lives with Wife in Idaho
 
:::

::: {.column width="50%"}
**Meds**: eplerenone, empagliflozin, digoxin 125, apixaban, atorvastatin, amiodarone 200, sacubitril-valsartan

**Exam**: 130s/70s, HR 70s, 95% on room air. NAD, AOx4. Systolic murmur II/VI. Clear lungs. Gait intact. 

**Studies**:  TTE in 09/2024 with LVEF of 35%, ++LA, +AS, +AI. CIED interrogation with ~70% AP and ~20% VP and 0% AF/AMS episodes.
:::
::::

## {background-image="fandell-pre-cxr.png" background-size="contain"}

## {background-image="fandell-pre-ecg-ap-vs.png" background-size="contain"}

# Electrocardiography {background-color='{{< brand color primary >}}'}

## {background-image="ecg-pvc-morphology.png" background-size="contain"}
## {background-image="ecg-12-lead-bigeminy.png" background-size="contain"}

# Baseline Electrograms {background-color='{{< brand color primary >}}'}

## {background-image="baseline-cs-far-field-pvc-earliest-proximally.png" background-size="contain"}
## {background-image="baseline-grid-catheter-early-to-pvc.png" background-size="contain"}
## {background-image="baseline-pacing-with-ablator.png" background-size="contain"}

# Maps {background-color='{{< brand color primary >}}'}

## {background-image="map-starting-with-grid.jpg" background-size="contain"}
## {background-image="map-grid-earliest-point.jpg" background-size="contain"}
## {background-image="map-bracketed.jpg" background-size="contain"}
## {background-image="map-ablation-location.jpg" background-size="contain"}
## {background-image="map-ablation-lesion-cloud.jpg" background-size="contain"}
## {background-image="map-heart-block.jpg" background-size="contain"}
## {background-image="map-final-lesions-60-ms-pre.jpg" background-size="contain"}
## {background-image="map-review-lesion-locations.jpg" background-size="contain"}

# Ablation {background-color='{{< brand color primary >}}'}

## Ablation details

- Used RF energy with a non-irrigated 4 mm tip catheter, power-limited at 50W with a target of 60˚C $\rightarrow$ *Sapphire*

- Ran into temperature limits, leading to low power output (5-15W)

- Switched to irrigated catheter $\rightarrow$ *FlexAbility* with improved applied energy

## {background-image="abl-50-sweep-a-no-v.png" background-size="contain"}
## {background-image="abl-back-on-after-av-recovery.png" background-size="contain"}
## {background-image="abl-final-5-sec.png" background-size="contain"}
## {background-image="abl-last-maybe-his-arrow.png" background-size="contain"}
## {background-image="abl-off-after-a-no-v-again.png" background-size="contain"}
## {background-image="abl-slow-junctionals.png" background-size="contain"}
## {background-image="abl-transition-to-vpacing-in-between-ablations.png" background-size="contain"}

# Hospital Course

## Summary

1. Day of presentation has device interrogation showing 0% AF burden, with 60-70% atrial pacing and 20-30% ventricular pacing with intact conduction.

1. Peri-annular PVC on posteroseptal side of tricuspid valve seen on ECG during EPS. Ablation performed using non-irrigated $\rightarrow$ irrigated catheter

1. Subsequent increase to 100% ventricular pacing without signs of native conduction

1. Following day recieved CRT-D upgrade and then discharged in appropriate condition

## {background-image="fandell-post-ecg-ap-vp.png" background-size="contain"}
## {background-image="fandell-post-cxr-ap.png" background-size="contain"}
## {background-image="fandell-post-cxr-lateral.png" background-size="contain"}
## {background-image="fandell-post-ecg-ap-bvp.png" background-size="contain"}